### ISSUE TITLE
vagrant up fails with bosh-lite VagrantFile

### ISSUE THREAD

**Issue by codemugal** [cloudfoundry/bosh-lite#227] opened 2014-12-26 02:33 UTC
I am trying to setup a local cloud foundry instance using bosh-lite on my mac laptop.

I unzipped the contents of bosh-lite-master ran the following command

see below

sh-3.2#vagrant up --provider=virtualbox

Error Message I got

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
default: Box Provider: virtualbox
default: Box Version: 2776
The box 'cloudfoundry/bosh-lite' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
vagrant login. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/cloudfoundry/bosh-lite"]
Error: 
sh-3.2#

**Comment by xtreme-andrei-dinin** [comment] 2015-01-02 20:29
Hi,
I just tried and could not reproduce the error. 

```
DX-191:tmp dx191$ cd bosh-lite/
DX-191:bosh-lite dx191$ vagrant up --provider=virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2776
==> default: Loading metadata for box 'cloudfoundry/bosh-lite'
    default: URL: https://vagrantcloud.com/cloudfoundry/bosh-lite
==> default: Adding box 'cloudfoundry/bosh-lite' (v2776) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/cloudfoundry/boxes/bosh-lite/versions/2776/providers/virtualbox.box
```

Did you want to try again and let us know if you are able to reproduce?

Thanks!

**Comment by mariash** [comment] 2015-01-03 00:16
This sounds similar to issue in this thread  https://groups.google.com/a/cloudfoundry.org/forum/m/#!topic/bosh-users/n2qYrpPUJaE

**Comment by cppforlife** [comment] 2015-01-06 22:08
We've pushed fix to master (c82c939833fd05ad8e7ad93595ece6d2a054f806). Please try again.

**Comment by xtreme-andrei-dinin** [comment] 2015-01-07 18:44
Added a point in the troubleshooting section for this.

**Comment by codemugal** [comment] 2015-01-08 00:30
Yes this is the same issue discussed in above link

**Closed** 2015-01-08 00:29 UTC
